name: "Nuke file"

on: 
  workflow_dispatch:
    inputs:
      filename:
        description: "File to wipe history for"
        required: true

permissions:
  contents: write

jobs:
  Execute:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '21'

      - name: Download BFG
        run: |
          url="https://repo1.maven.org/maven2/com/madgag/bfg"
          latestVersion=`curl -s $url/maven-metadata.xml | grep latest | sed "s/.*<latest>\([^<]*\)<\/latest>.*/\1/"`
          curl -s $url/$latestVersion/bfg-$latestVersion.jar -o bfg.jar
          
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          path: "repo"
          
      - name: Remove history
        run: |
          java -jar bfg.jar --no-blob-protection --delete-files ${{ inputs.filename }} repo
          cd repo
          git reflog expire --expire=now --all && git gc --prune=now --aggressive
          git config user.name github-actions
          git config user.email github-actions@github.com
          git commit --allow-empty -am "Removed file history"
          git push origin --force --all
          
